<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="ShiftEntry.aspx.cs" Inherits="ShiftEntry" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <fieldset>
        <legend><b>
                    <h2>
                        Shift Information</h2>
                </b></legend>
        <table class="style1">
            
            <%-- <tr>
                <td class="style4">
                    Class Name
                </td>
                <td class="style3">
                   
                    <asp:DropDownList ID="classDropDownList" runat="server" AppendDataBoundItems="True"
                        DataSourceID="SqlDataSource3" DataTextField="VarClassName" 
                        DataValueField="VarClassID">
                        <asp:ListItem Value="0">--Select Class--</asp:ListItem>
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource3" runat="server" 
                        ConnectionString="<%$ ConnectionStrings:SWISConnectionString %>" 
                        SelectCommand="SELECT * FROM [Class]"></asp:SqlDataSource>
                </td>
            </tr>--%>
            <tr>
                <td class="style4">
                    Shift Code
                </td>
                <td class="style3">
                   
                    <asp:TextBox ID="txtShiftCode" runat="server" Width="130px"></asp:TextBox>
                    <br />
                </td>
            </tr>
            <tr>
                <td class="style4">
                    Shift Name
                </td>
                <td class="style3">
                   
                    <asp:TextBox ID="txtShiftName" runat="server" Width="130px"></asp:TextBox>
                    <br />
                </td>
            </tr>
            <br />
            <tr>
                <td class="style4">
                    <asp:Button ID="shiftSave" runat="server" Text="Save" Width="81px" 
                                OnClientClick=" return validate(); " onclick="shiftSave_Click"
                        />
                </td>
                <td class="style3">
                    <asp:Literal ID="Literal1" runat="server"></asp:Literal>
                    
                </td>
            </tr>
        </table>
    </fieldset>


    <fieldset>
        <legend><b>
                    <h2>
                        Shift Information Details</h2>
                </b></legend>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True"
                      DataKeyNames="VarShiftCode" DataSourceID="SqlDataSource1" 
                      AutoGenerateEditButton="True" AutoGenerateColumns="False" CellPadding="4" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="VarShiftCode" HeaderText="Shift Code" 
                                ReadOnly="True" SortExpression="VarShiftCode" />
                <asp:BoundField DataField="VarShiftName" HeaderText="Shift Name" 
                                SortExpression="VarShiftName" />
                <%--<asp:TemplateField HeaderText="Class Name" SortExpression="VarClassId">
               
                <ItemTemplate>
                    <asp:DropDownList ID="DropDownList1" runat="server" 
                        DataSourceID="SqlDataSource1" DataTextField="VarClassName" 
                        DataValueField="VarClassID" SelectedValue='<%# Bind("VarClassID") %>'>
                    </asp:DropDownList>
                    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                        ConnectionString="<%$ ConnectionStrings:SWISConnectionString %>" 
                        SelectCommand="SELECT * FROM [Class]"></asp:SqlDataSource>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="uid" HeaderText="User Name" ReadOnly="True" 
                SortExpression="uid" />--%>
            </Columns>
            <EditRowStyle BackColor="#7C6F57" />
            <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#E3EAEB" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F8FAFA" />
            <SortedAscendingHeaderStyle BackColor="#246B61" />
            <SortedDescendingCellStyle BackColor="#D4DFE1" />
            <SortedDescendingHeaderStyle BackColor="#15524A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                           ConnectionString="<%$ ConnectionStrings:SWISConnectionString %>" 
        
                           SelectCommand="SELECT [VarShiftCode], [VarShiftName], [VarClassId], [uid] FROM [ShiftInfo]" 
                           DeleteCommand="DELETE FROM [ShiftInfo] WHERE [VarShiftCode] = @VarShiftCode" 
                           InsertCommand="INSERT INTO [ShiftInfo] ([VarShiftCode], [VarShiftName], [VarClassId], [uid]) VALUES (@VarShiftCode, @VarShiftName, @VarClassId, @uid)" 
                           UpdateCommand="UPDATE [ShiftInfo] SET [VarShiftCode] = @VarShiftCode, [VarShiftName] = @VarShiftName, [VarClassId] = @VarClassId WHERE [VarShiftCode] = @VarShiftCode">
            <DeleteParameters>
                <asp:Parameter Name="VarShiftCode" Type="String" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="VarShiftCode" Type="String" />
                <asp:Parameter Name="VarShiftName" Type="String" />
                <asp:Parameter Name="VarClassId" Type="String" />
                <asp:Parameter Name="uid" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="VarShiftName" Type="String" />
                <asp:Parameter Name="VarClassId" Type="String" />
                <asp:Parameter Name="uid" Type="String" />
                <asp:Parameter Name="VarShiftCode" Type="String" />
            </UpdateParameters>
        </asp:SqlDataSource>

    </fieldset>
</asp:Content>